title: 株式会社ジーンズエムシーディ｜秋田のデニム・ジーンズ洗い加工
description: 株式会社ジーンズエムシーディは、秋田県秋田市を拠点にジーンズ・デニムの洗い加工、レーザー加工、染色・脱色加工などを行う生産拠点です。サステナブルな加工技術の研究開発にも取り組んでいます。
url: https://j-mcd3115.github.io
baseurl: /mcd

defaults:
  - scope:
      path: ""
    values:
      layout: default
